### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by SaiKishore2** [ChaseFlorell/jQuery.ProfanityFilter#13]
While I am performing the profanity filter on the text it is getting uncaught error and closing , do we need any plugin for profanity filter.

**Comment by ChaseFlorell** [comment]
Do you have jquery available?

**Comment by ChaseFlorell** [comment]
@SaiKishore2  can you please post some example code for me? Otherwise, if you've sorted this out, we can close the issue.

**Comment by ChaseFlorell** [comment]
Didn't hear back. Closing.
