### ISSUE TITLE
How to change the style of the profane words?

### ISSUE THREAD

**Issue by glennax** [ChaseFlorell/jQuery.ProfanityFilter#14]
Trying to figure out how to make the profane words turn red instead of replacing them with *, but no luck. Ideas?

**Comment by ChaseFlorell** [comment]
good question. I'd have to take a look.

**Comment by ChaseFlorell** [comment]
@glennax will the latest PR do what you're asking?
Take a look at the [demo page](https://chaseflorell.github.io/jQuery.ProfanityFilter/demo)

**Comment by glennax** [comment]
@ChaseFlorell Thank you for getting back to me! However, what i would like to do is only highlight all the individual profane words found in the text. Would it be possible?

**Comment by ChaseFlorell** [comment]
I just published a version that adds an array of bad words to the callback (see example #5 of the [demo page](https://chaseflorell.github.io/jQuery.ProfanityFilter/demo/)).

Use that callback to string.replace the words with styled ones.

**Comment by ChaseFlorell** [comment]
Try this fiddle.

https://jsfiddle.net/rockinthesixstring/Lqruyncw/
