### ISSUE TITLE
Profanity Filter is not working

### ISSUE THREAD

**Issue by SaiKishore2** [ChaseFlorell/jQuery.ProfanityFilter#16]
I am using the profanityFilter in my code but it is not at all filtering the words. I included jquery.ProfanityFilter and jquery.ProfanityFilter.min.js , swearWords.json files in my code  can you please help me??

**Comment by ChaseFlorell** [comment]
you don't need to include both the basic and the min versions, one will do. Also, please ensure you are including jquery.js

https://jsfiddle.net/rockinthesixstring/s3ss17cu/
