### ISSUE TITLE
Different external swear word files aren't allowed

### ISSUE THREAD

**Issue by JohanBengtsson** [ChaseFlorell/jQuery.ProfanityFilter#21]
Since the external swear word files are stored in local storage with the same key "localSwears" it is not possible to use different external swear words files in the same browser/host name. I have fixed this on a local branch with 

```javascript
...

                data = [],
                localSwearsKey = 'localSwears' + options.externalSwears;

            if (options.externalSwears !== null) {
                if (localStorageIsEnabled) {
                    if (localStorage.getItem(localSwearsKey) === null) {
                        // stringify the array so that it can be stored in local storage
                        localStorage.setItem(localSwearsKey, JSON.stringify(readJsonFromController(options.externalSwears)));
                    }
                    badWords = JSON.parse(localStorage.getItem(localSwearsKey));
                } else {

...
```

in `jquery.ProfanityFilter.js`

**Comment by ChaseFlorell** [comment]
This looks good, would you also consider adding a PR on this as well?

**Comment by JohanBengtsson** [comment]
Sure, just give me the access rights @ChaseFlorell

**Comment by ChaseFlorell** [comment]
It's just a pull request.

Fork the repo to your own account.
Make the changes
Submit a PR.

**Comment by JohanBengtsson** [comment]
Ah ok, I'll try that, thanks. New to this process :)

**Comment by ChaseFlorell** [comment]
#23 closes this issue.

**Comment by JohanBengtsson** [comment]
Actually https://github.com/ChaseFlorell/jQuery.ProfanityFilter/pull/24 closes this issue

**Comment by ChaseFlorell** [comment]
My Mistake.
Always good to add it in the PR message... I just overlooked it.
