### ISSUE TITLE
localStorageIsEnabled doesn't work

### ISSUE THREAD

**Issue by JohanBengtsson** [ChaseFlorell/jQuery.ProfanityFilter#22]
On my computer (Mac OsX) and browser (Chrome) the localStorageIsEnabled doesn't work since the date comparison is too strict, and thus the Ajax request to get the external swear words is made for every word which has a bad performance effect. 

We have fixed this locally by changing the `result` comparison to

```javascript
result = localStorage.getItem("uid") == uid;
```

instead of 

```javascript
result = localStorage.getItem("uid") === uid;
```

**Comment by ChaseFlorell** [comment]
would you submit a PR on this?

**Comment by JohanBengtsson** [comment]
Sure! can you give me the access rights? I have a branch prepared since weeks ago but lack the permission to upload new branches to your repo @ChaseFlorell
