### ISSUE TITLE
How to apply if else loop to the filter

### ISSUE THREAD

**Issue by Dhrumilkp** [ChaseFlorell/jQuery.ProfanityFilter#28]
I am not an expert here, but i want to know how can i add if else so in case if there is swear in the line it will disabled the button and enable after a check if there is not swear words

**Comment by ChaseFlorell** [comment]
If you look at the [demo](https://chaseflorell.github.io/jQuery.ProfanityFilter/demo/), there's a callback function that is invoked around the profaneText.

```js
// code:
$('#five').profanityFilter({
    customSwears: ['ass'],
    filter: true,
    externalSwears: 'swearWords.json',
    profaneText: function(data) {
        $('#five')
            .css('color', 'blue');
            console.log(data);
    }
});
```

you can do whatever you like within the callback, so I suggest just disabling the button in there.
